### PR TITLE
New parameters in server.cfg to use custom port or to disable log to console

### PR DESCRIPTION
**Pull request by abdalmoez**
-  New parameters:

sv_log_to_console  false           =>   Will disable log to server_log.txt and to console (default: true)
sv_port  [port]                          =>   Use Custom port by default use random value 

- Display year month and day in svlog.txt

### CODE REVIEW

**Comment by ZTzTopia** [comment]
very nice

**Comment by BenasPaulikas** [comment]
+1 for merge and release :)

**Comment by BenasPaulikas** [comment]
@abdalmoez thank you! :)

**Comment by AbdulOmarCR** [comment]
Awesome

**Comment by mhyunata** [comment]
can u give me the compiled version for the include and plugin that u have changed?

**Comment by ditampol-tzuyoon** [comment]
can u gimme the compiled version for the include and plugin that u have changed?

**Comment by ditampol-tzuyoon** [comment]
Hi @abdalmoez 
can u gimme the compiled version for the include and plugin that u have changed? i not have more storage to installing Visual Studio

**Comment by LevanBedinashvili** [comment]
can you give me compiled version of this plugin?

**Pull request closed without merging**
