### PR TITLE
Updated to 0.3DL

### PR DESCRIPTION
**Pull request by ZTzTopia**
I've updated the sampvoice to 0.3DL

### CODE REVIEW

**Comment by ZTzTopia** [comment]
Download: https://www.mediafire.com/folder/3dk8trr6wkmcg/sampvoice+0.3DL

**Comment by ZTzTopia** [comment]
Download: https://www.mediafire.com/folder/3dk8trr6wkmcg/sampvoice+0.3DL

**Review by duydang2311 — APPROVED** [review]

**Comment by K3ll6** [comment]
image
successful connection but key press does not work

**Comment by Nickk888SAMP** [comment]
Hey, good work porting it to 0.3DL! Do you maybe have the installer version for both client and server?

**Comment by Fariz0077** [comment]
Hey Can I Get The Compiled Plugin For 0.3DL

**Comment by AthallahDzaki** [comment]
Current Project
 - [ ] Client Support
 - [x] Server Support

**Pull request closed without merging**
